## Assignment No : 1


#### Q1. Write code to create a 4x3 matrix with values ranging from 2 to 13.

In [1]:
import numpy as np

In [4]:
arr1 = np.arange(2,14).reshape(4,3)
arr1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

#### Q2.Write code to replace the odd numbers by -1 in the array created by using random.randint( 1 , 50, 20)

In [3]:
a = np.random.randint(1, 50, 20)
a[a % 2 == 0] = -1
a

array([ 5,  7, 29, -1, -1, -1, 49, 29,  7, 15,  5, -1, 29, -1, -1,  7, -1,
       -1,  5,  7], dtype=int32)

#### Q3. Perform the following operations on an array of mobile phones prices 6999, 7500, 11999, 27899, 14999, 9999.
 #### a. Create a 1d-array of mobile phones prices

In [5]:
prices = np.array([6999,7500,11999,27899,14999,9999])
prices

array([ 6999,  7500, 11999, 27899, 14999,  9999])

#### b. Convert this array to float type

In [6]:
prices_float = prices.astype(float)
prices_float

array([ 6999.,  7500., 11999., 27899., 14999.,  9999.])

#### c. Append a new mobile having price of 13999 Rs. to this array

In [7]:
prices_new = np.append(prices, 13999)
prices_new

array([ 6999,  7500, 11999, 27899, 14999,  9999, 13999])

#### d. Reverse this array of mobile phones prices

In [8]:
rev_arr = prices_new[::-1]
rev_arr

array([13999,  9999, 14999, 27899, 11999,  7500,  6999])

#### e. Apply GST of 18% on mobile phones prices and update this array.

In [9]:
GST_arr = prices_new * 1.18
GST_arr

array([ 8258.82,  8850.  , 14158.82, 32920.82, 17698.82, 11798.82,
       16518.82])

#### f. Sort the array in descending order of price

In [13]:
sort_desc = np.sort(prices_new)[::-1]
sort_desc

array([27899, 14999, 13999, 11999,  9999,  7500,  6999])

#### g. What is the average mobile phone price

In [15]:
avg_price = np.mean(prices_new)
avg_price

np.float64(13342.0)

#### h. What is the difference b/w maximum and minimum price

In [16]:
difference = prices_new.max() - prices_new.min()
difference

np.int64(20900)

#### 4. Find out the indices of non zero element in given array [1,2,0,0,4,0]

In [17]:
arr = np.array([1,2,0,0,4,0])
indices = np.nonzero(arr)
indices

(array([0, 1, 4]),)